# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3e518024ffd32e55d7d2e59e760f081e9468867a0f4f308ef2b711f96d0b6db461b4dca07c16d2a39f8df86c0e9690fdf43adb054a764cddc89816302af5fbd

test:
  secret_key_base: 7def569df181df6fa5f634363c853d5e944df3601b99a0c0d3706719e64b25b5db3fd2ae4ed07f1659cd2ffd1147e4d0e2b84e982f4848776bfaf0272ae0462f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
